title = "Bay Area Mountain Rescue Unit"
baseURL = "/"
languageCode = "en-us"
theme = "airspace-hugo"

# The site's parameters
[params]
  home = "Home"
  
  [menu]

    [[menu.header]]
      weight = 2
      name = "About"
      url = "/about"
    [[menu.header]]
      weight = 3
      name = "Join"
      url = "/join"
    [[menu.header]]
      weight = 4
      name = "Meet Us"
      url = "/meet"
    [[menu.header]]
      weight = 5
      name = "Trainings"
      url = "/train"


    [[menu.footer]]
      weight = 1
      name = "Donate"
      url = "#"
    [[menu.footer]]
      weight = 2
      name = "Calendar"
      url = "#"
    [[menu.footer]]
      weight = 3
      name = "Contact us"
      url = "#"
    [[menu.footer]]
      weight = 4
      name = "Blog"
      url = "#"
    [[menu.footer]]
      weight = 5
      name = "Partners"
      url = "#"

  [params.slider]
    enable = true
    title = "Bay Area Mountain Rescue Unit"
    subtitle = "BAMRU is a volunteer wilderness search and rescue team specializing in difficult terrain, challenging weather, and high altitude.  We are based in the San Francisco Bay Area and operate throughout California."
    bgImage = "img/slider-bg.jpg"
    btnText = "Learn More"
    url = "#"

  [params.wrapper]
    enable = true
    image = "img/wrapper-img.png"
    title = "About BAMRU"
    italic = "BAMRU is an all-volunteer wilderness search and rescue (SAR) unit, based in the San Francisco Bay Area. We look for and help people lost or stranded anywhere outdoors in California."
    paragraph = "Members of BAMRU are climbers, mountaineers, backpackers and skiers who train in a variety of skills used for wilderness search and rescue. BAMRU members live all over the Bay Area, from Marin to Santa Cruz and from San Francisco to Contra Costa County. BAMRU is an accredited member of the Mountain Rescue Association and is a FEMA and California OES Type I search and rescue resource. This means that we have the ability to operate safely and effectively, night or day, in all terrain, in all weather, in all seasons."

    
  [params.feature]
    enable = true
    title = "Anytime, Anywhere, All Conditions"
    bgImage = "img/feature-bg.jpg"
    content = "As a technical rescue team, BAMRU has the skills necessary for low- and high-angle rescue operations. BAMRU members are continually advancing their skills in the disciplines of tracking, search operation management, and wilderness medicine. Our experience allows us to work safely and comfortably in any challenging and hazardous wilderness situations."
    [params.feature.button]
      caption = "View Trainings"
      url = "/train"

  [params.call]
    enable = false
    bgImage = "img/call-to-action-bg.jpg"
    title = "Apply to be a Trainee"
    paragraph = "BAMRU members are women and men who share a desire to put their specialized outdoors skills to use in the service of people missing or injured in the wilderness. Self-sufficiency is a trademark of BAMRU. When called upon, members are prepared to operate for up to 72 hours in the field and without support. Trainees take 2+ years to become field members. We do this on top of our day jobs and family responsibilities. Are you ready for that?"
    [params.call.button]
      url = "/join"
      text = "find out how to apply"