title = "Bay Area Mountain Rescue Unit"
baseURL = "/"
languageCode = "en-us"
theme = "airspace-hugo"

# The site's parameters
[params]
  home = "Home"
  
  [menu]

    [[menu.header]]
      weight = 2
      name = "About"
      url = "/about"
    [[menu.header]]
      weight = 3
      name = "Services"
      url = "/services"
      [[menu.header]]
      weight = 4
      name = "Join"
      url = "/join"
    [[menu.header]]
      weight = 5
      name = "Meet Us"
      url = "/meet"

    [[menu.footer]]
      weight = 1
      name = "Donate"
      url = "/donate"
    [[menu.footer]]
      weight = 2
      name = "Calendar"
      url = "/calendar"
    [[menu.footer]]
      weight = 3
      name = "Contact us"
      url = "/contact"
    [[menu.footer]]
      weight = 4
      name = "Partners"
      url = "/partners"
    [[menu.footer]]
      weight = 5
      name = "Facebook"
      url = "https://www.facebook.com/Bay-Area-Mountain-Rescue-Unit-BAMRU-285355628178842/"
    [[menu.footer]]
      weight = 6
      name = "LinkedIn"
      url = "https://www.linkedin.com/company/bamru/"
    [[menu.footer]]
      weight = 7
      name = "Twitter"
      url = "https://twitter.com/BAMRUorg/"
    [[menu.footer]]
      weight = 8
      name = "Instagram"
      url = "https://www.instagram.com/bamru/"
    [[menu.footer]]
      weight = 9
      name = "Blog"
      url = "https://bamru.blogspot.com/"

  [params.slider]
    enable = true
    title = "Bay Area Mountain Rescue Unit"
    subtitle = "BAMRU is an all-volunteer, non-profit wilderness search and rescue team specializing in operations involving difficult terrain, challenging weather conditions and high altitude. We are affiliated with the San Mateo County Sheriff’s Office and operate throughout California.<br><br>45+ years of service <br> 20+ yearly operations <br> 50+ active members <br> 16000+ hours volunteered per year"
    bgImage = "img/slider-bg.jpg"
    btnText = "Learn More"
    url = "/about"

  [params.wrapper]
    enable = true
    image = "img/logo-square.png"
    title = "About BAMRU"
    italic = "BAMRU is an all-volunteer wilderness search and rescue (SAR) unit, based in the San Francisco Bay Area. We look for and help people lost or stranded anywhere outdoors in California."
    paragraph = "Members of BAMRU are trained in a variety of skills used for wilderness search and rescue. BAMRU members live all over the Bay Area, from Marin to Santa Cruz and from San Francisco to Contra Costa County. BAMRU is an accredited member of the Mountain Rescue Association and is a FEMA and California OES Type I search and rescue resource. This means that we have the ability to operate safely and effectively, night or day, in all terrain, in all weather, in all seasons."
    
  [params.feature]
    enable = true
    title = "Anytime, Anywhere, All Conditions"
    bgImage = "img/feature-bg.jpg"
    content = "BAMRU is field deployable for up to 72 hours for anyone in harm’s way in all terrain, all weather and all seasons. Operations range from searches for missing or lost individuals in the high Sierra to communities affected by wildfires.  In addition to mountains, we search along coastal cliffs and in other rural and wilderness environments. Our team is composed of rock climbers, mountaineers, backpackers and backcountry skiers.  Our members are skilled to operate efficiently and safely in technical terrain on rock, snow and ice. BAMRU is an accredited member of the Mountain Rescue Association and a FEMA and California OES Type I search and rescue resource.  We are activated for operations by the San Mateo County Sheriff’s Office."
  
    [params.feature.button]
      caption = "What does BAMRU do?"
      url = "/services"

  [params.contact.box]
    title = "How to get in touch with us:"
    address = "Bay Area Mountain Rescue Unit, PO Box 19184, Stanford CA, 94309"
    email = "info@bamru.org"
    recruit = "recruiting@bamru.org"
    phone = "please call 911 to report a missing person"
  
  [params.call]
    enable = false
    bgImage = "img/call-to-action-bg.jpg"
    title = "Get Involved"
    paragraph = "BAMRU serves our community by searching for those lost or injured in the wilderness. The team consists of volunteers who train for hundreds of hours each year to operate under stressful and rapidly changing weather and circumstances. While each member does not attend every operation, being on the team requires a significant time commitment and some flexibility with job and family responsibilities. If you are interested in joining the team, attend one of our meetings, which are open for guests."
    [params.call.button]
      url = "/join"
      text = "Learn how to apply"
    
