name: update-calendar
on:
  schedule:
    - cron: '0 * * * *'

jobs:
  update_repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: sources

      - name: Setup Python
        uses: actions/setup-python@v2

      - name: Install packages
        run: pip install -r ${{ github.workspace }}/requirements.txt

      - name: Update calendar
        run: python ${{ github.workspace }}/cal.py > ${{ github.workspace }}/data/calendar.yml

      - name: Cancel if no changes
        run: if git diff --quiet; then echo "no chages"; false; fi

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 0.86.0

      - name: Build
        run: hugo

      - name: Commit
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m 'Update calendar'
          git push origin sources

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: master
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
