name: update-calendar
on:
  push:
    branches:
      - sources

jobs:
  update_repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: sources

      - name: Setup Python
        uses: actions/setup-python@v2

      - name: Install packages
        run: pip install -r ${{ github.workspace }}/requirements.txt

      - name: Update calendar
        run: python ${{ github.workspace }}/cal.py > ${{ github.workspace }}/data/calendar.yml

      - name: Detect changes
        id: detect_changes
        run: |
          if git diff --quiet; then
            echo "::set-output name=updated::false"
          else
            echo "::set-output name=updated::true"
          fi

      - name: Setup Hugo
        if: ${{ steps.detect_changes.updated == 'true' }}
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 0.86.0

      - name: Build
        if: ${{ steps.detect_changes.updated == 'true' }}
        run: hugo

      - name: Commit
        if: ${{ steps.detect_changes.updated == 'true' }}
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m 'Update calendar'
          git push origin sources

      - name: Deploy
        if: ${{ steps.detect_changes.updated == 'true' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: master
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
