name: update-calendar
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update_repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: master

      - name: Setup Python
        uses: actions/setup-python@v4

      - name: Install packages
        run: pip install -r ${{ github.workspace }}/requirements.txt

      - name: Update calendar
        run: python ${{ github.workspace }}/cal.py > ${{ github.workspace }}/data/calendar.yml

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 0.86.0

      - name: Build
        run: hugo

      - name: Detect changes
        id: detect_changes
        run: |
          if git diff --quiet; then
            echo "{updated}={false}" >> $GITHUB_OUTPUT
          else
            echo "{updated}={true}" >> $GITHUB_OUTPUT
          fi

      - name: Commit
        if: ${{ steps.detect_changes.outputs.updated == 'true' }}
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m 'Update calendar'
          git push origin master

      - name: Deploy
        if: ${{ steps.detect_changes.outputs.updated == 'true' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
